

-- CreateTable
CREATE TABLE chat (
    id VARCHAR(32) PRIMARY KEY,
    user_id VARCHAR(32) NOT NULL,
    title  TEXT NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE message (
    id VARCHAR(32) PRIMARY KEY NOT NULL,
    chat_id VARCHAR(32) NOT NULL,
    content TEXT NOT NULL,
    links VARCHAR(300)[],
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assistant BOOLEAN NOT NULL,
    FOREIGN KEY (chat_id) REFERENCES chat(id)
);