
ALTER TABLE mensagens ADD CONSTRAINT "Mensagem_idChat_fkey" FOREIGN KEY (id_chat) REFERENCES chats("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE chats ADD CONSTRAINT "Chat_idUsuario_fkey" FOREIGN KEY (id_usuario) REFERENCES usuarios("id") ON DELETE RESTRICT ON UPDATE CASCADE;
