basePath: /
definitions:
  auth_dto.AuthResponseDto:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/auth_dto.UserDto'
    type: object
  auth_dto.LoginRequestDto:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  auth_dto.RegisterRequestDto:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  auth_dto.UserDto:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    type: object
  chat_dto.ChatDto:
    properties:
      createdAt:
        type: string
      id:
        type: string
      title:
        type: string
      updatedAt:
        type: string
      userId:
        type: string
    type: object
  chat_dto.CreateChatDto:
    properties:
      title:
        type: string
    type: object
  chat_dto.CreateMensagemDto:
    properties:
      content:
        type: string
    type: object
  chat_dto.ListChatDto:
    properties:
      data:
        items:
          $ref: '#/definitions/chat_dto.ChatDto'
        type: array
      limit:
        example: 10
        maximum: 100
        minimum: 1
        type: integer
      page:
        example: 1
        minimum: 1
        type: integer
      total:
        type: integer
    type: object
  chat_dto.ListMessageDto:
    properties:
      data:
        items:
          $ref: '#/definitions/chat_dto.MessageDto'
        type: array
      limit:
        example: 10
        maximum: 100
        minimum: 1
        type: integer
      page:
        example: 1
        minimum: 1
        type: integer
      total:
        type: integer
    type: object
  chat_dto.MessageDto:
    properties:
      assistant:
        type: boolean
      chatId:
        type: string
      content:
        type: string
      createdAt:
        type: string
      id:
        type: string
    type: object
  util_dto.AppResponse:
    properties:
      data: {}
      message:
        type: string
      statusCode:
        type: integer
    type: object
info:
  contact: {}
  description: Documentação do melhor chatbot universitario
  title: Golang CHATBOT
  version: '@0.0.1'
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Autentica um usuário com email e senha
      parameters:
      - description: Credenciais de login
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth_dto.LoginRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: Retorna um token JWT
          schema:
            allOf:
            - $ref: '#/definitions/util_dto.AppResponse'
            - properties:
                data:
                  $ref: '#/definitions/auth_dto.AuthResponseDto'
              type: object
      summary: Login
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Autentica um usuário com email e senha
      parameters:
      - description: Credenciais de login
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth_dto.RegisterRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: Retorna um token JWT
          schema:
            allOf:
            - $ref: '#/definitions/util_dto.AppResponse'
            - properties:
                data:
                  $ref: '#/definitions/auth_dto.AuthResponseDto'
              type: object
      summary: Cadastro de usuário
      tags:
      - Auth
  /chats/{chatID}/list-messages:
    get:
      consumes:
      - application/json
      parameters:
      - example: 10
        in: query
        maximum: 100
        minimum: 1
        name: limit
        type: integer
      - example: 1
        in: query
        minimum: 1
        name: page
        type: integer
      - in: query
        name: total
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Lista de chats
          schema:
            allOf:
            - $ref: '#/definitions/util_dto.AppResponse'
            - properties:
                data:
                  $ref: '#/definitions/chat_dto.ListMessageDto'
              type: object
        "404":
          description: Nenhum chat encontrado
          schema:
            $ref: '#/definitions/util_dto.AppResponse'
      summary: Listar mensagens
      tags:
      - Chats
  /chats/{chatID}/new-message:
    post:
      consumes:
      - application/json
      description: Envia uma nova mensagem dentro de um chat existente
      parameters:
      - description: ID do chat
        in: path
        name: chatID
        required: true
        type: string
      - description: Dados da mensagem
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/chat_dto.CreateMensagemDto'
      produces:
      - application/json
      responses:
        "200":
          description: Resposta da IA
          schema:
            allOf:
            - $ref: '#/definitions/util_dto.AppResponse'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Erro de validação ou requisição
          schema:
            $ref: '#/definitions/util_dto.AppResponse'
      summary: Enviar mensagem para um chat
      tags:
      - Chats
  /chats/list-chats:
    get:
      consumes:
      - application/json
      description: Lista chats aplicando filtros opcionais
      parameters:
      - example: 10
        in: query
        maximum: 100
        minimum: 1
        name: limit
        type: integer
      - example: 1
        in: query
        minimum: 1
        name: page
        type: integer
      - in: query
        name: total
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Lista de chats
          schema:
            allOf:
            - $ref: '#/definitions/util_dto.AppResponse'
            - properties:
                data:
                  $ref: '#/definitions/chat_dto.ListChatDto'
              type: object
        "404":
          description: Nenhum chat encontrado
          schema:
            $ref: '#/definitions/util_dto.AppResponse'
      summary: Listar chats
      tags:
      - Chats
  /chats/new-chat:
    post:
      consumes:
      - application/json
      description: Cria um novo chat com título e usuário associado
      parameters:
      - description: Dados para criar chat
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/chat_dto.CreateChatDto'
      produces:
      - application/json
      responses:
        "200":
          description: Chat criado com sucesso
          schema:
            allOf:
            - $ref: '#/definitions/util_dto.AppResponse'
            - properties:
                data:
                  $ref: '#/definitions/chat_dto.ChatDto'
              type: object
        "400":
          description: Erro de validação ou requisição
          schema:
            $ref: '#/definitions/util_dto.AppResponse'
      summary: Criar novo chat
      tags:
      - Chats
securityDefinitions:
  Bearer Auth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
