basePath: /
definitions:
  auth_dto.LoginRequestDto:
    properties:
      login:
        type: string
      senha:
        type: string
    type: object
host: localhost:4000
info:
  contact: {}
  description: Documentação do melhor chatbot do mundo2
  title: Minha API
  version: 0.0.1
paths:
  /cadastrar:
    post:
      consumes:
      - application/json
      description: Eu acho que cadastra um usuário
      parameters:
      - description: User credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/auth_dto.LoginRequestDto'
      produces:
      - application/json
      responses: {}
      summary: Cadastra um usuário
      tags:
      - Autenticação
  /login:
    post:
      consumes:
      - application/json
      description: Recebe login e senha para autenticar
      parameters:
      - description: User credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/auth_dto.LoginRequestDto'
      produces:
      - application/json
      responses: {}
      summary: Autentica um usuário
      tags:
      - Autenticação
swagger: "2.0"
